# Generated by Django 5.0.6 on 2026-08-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Se genera automáticamente. Ej: steel-framing', max_length=100, unique=True, verbose_name='Slug (URL)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve visible en la galería.', verbose_name='Descripción')),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Río Tercero, Córdoba', max_length=200, verbose_name='Ubicación')),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('superficie', models.CharField(blank=True, help_text='Ej: 80 m²', max_length=50, verbose_name='Superficie')),
                ('foto_portada', models.ImageField(help_text='Imagen principal que se muestra en la galería.', upload_to='proyectos/', verbose_name='Foto de portada')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Última edición')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='proyectos.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='FotoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='proyectos/galeria/', verbose_name='Foto')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Foto de proyecto',
                'verbose_name_plural': 'Fotos de proyecto',
                'ordering': ['orden'],
            },
        ),
    ]
