# Generated by Django 5.0.6 on 2026-08-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('servicio', models.CharField(blank=True, choices=[('steel', 'Steel framing'), ('drywall', 'Drywall / cielorrasos'), ('revestimientos', 'Revestimientos'), ('eps', 'EPS Revestimiento'), ('stands', 'Stands para ferias'), ('otro', 'Otro / no estoy seguro')], max_length=50, verbose_name='Servicio consultado')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-fecha'],
            },
        ),
    ]
